// src/components/works.tsx
"use client"
import { useState } from "react";
import Styles from "@/src/css/works.module.css"
import Image from "next/image";

// Images
import megabetLogo from "@/public/assets/img/logo/megabet_logo_single.webp"
import cgmLogo from "@/public/assets/img/logo/cgm.webp"
import asiatypeLogo from "@/public/assets/img/logo/asiatype.webp"

function gotoMegabet() {
    window.open('https://megabet-paradise.com/', '_blank');
}
const Work = () => {
    
    const [modal, setModal] = useState(false)
    const modalShow = ()=> {
        setModal(true)
    }
    const modalHide = ()=> {
        setModal(false)
    }
    return(
        <>
        <div className={Styles.sectionTitle}>Works</div>
        <div className={Styles.projectList}>
            <div className={`${Styles.listItem} ${Styles.active}`} onClick={modalShow}>
                <div className={Styles.logo}>
                    <Image src={megabetLogo} alt="megabet"/>
                </div>
                <div className={Styles.name}>
                    <div className={Styles.title}>Megabet<span>(VueJS)</span></div>
                    <div className={Styles.subTitle}>Layout, Screen Responsiveness & Reactive.</div>
                </div>
                <div className={Styles.action}>{'>'}</div>
            </div>
            <div className={Styles.listItem}>
                <div className={Styles.logo}>
                    <Image src={cgmLogo} alt="cgm manila"/>
                </div>
                <div className={Styles.name}>
                    <div className={Styles.title}>Circle Graphics</div>
                    <div className={Styles.subTitle}>Data Conversion, Macros.</div>
                </div>
            </div>
            <div className={Styles.listItem}>
                <div className={Styles.logo}>
                    <Image src={asiatypeLogo} alt="asiatype"/>
                </div>
                <div className={Styles.name}>
                    <div className={Styles.title}>Asiatype</div>
                    <div className={Styles.subTitle}>Data Conversion, Macros.</div>
                </div>
            </div>
        </div>
        {modal &&
            <div className={Styles.megabetDemo}>
                <div className="modalCard">
                    <div className="modalHeader">
                        <div>Megabet Walkthrough</div>
                        <button onClick={modalHide}>CLOSE</button>
                    </div>
                    <div className="modalBody">
                        <iframe 
                        src="https://www.youtube.com/embed/4Fx50rICEkE?si=RH32sciunTk1kcqq" 
                        title="YouTube video player"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
                        referrerPolicy="strict-origin-when-cross-origin" 
                        allowFullScreen
                    ></iframe>
                    </div>
                    <div className="modalFooter">Project link: <button onClick={gotoMegabet}>Megabet Website</button></div>
                </div>
            </div>
        }
        </>
    )
}

export default Work

// src/components/content-section/works.vue
<script setup lang="ts">
 function gotoMegabet() {
    window.open('https://megabet-paradise.com/', '_blank');
 }
</script>
<template>
  <section id="project">
    <div class="section-title">Works</div>
    <div class="project-list">
      <div class="list-item active" @click="gotoMegabet">
        <div class="logo">
          <img src="@/assets/img/logo/megabet_logo_single.webp" alt="megabet">
        </div>
        <div class="name">
          <div class="title">Megabet</div>
          <div class="sub-title">Layout, Screen Responsiveness, Reactive.</div>
        </div>
        <div class="action">></div>
      </div>
      <div class="list-item">
        <div class="logo">
          <img src="@/assets/img/logo/cgm.webp" alt="circke_graphics">
        </div>
        <div class="name">
          <div class="title">Circle Graphics</div>
          <div class="sub-title">Data Conversion, Macros.</div>
        </div>
        <div class="action"></div>
      </div>
      <div class="list-item">
        <div class="logo">
          <img src="@/assets/img/logo/asiatype.webp" alt="circke_graphics">
        </div>
        <div class="name">
          <div class="title">Asiatype</div>
          <div class="sub-title">Data Conversion, Macros.</div>
        </div>
        <div class="action"></div>
      </div>
    </div>
  </section>
</template>
<style scoped>
.project-list {
  height: 100%;
  width: 100%;
  background: #f0f0f0;
  padding: 1.5em 1em;
  margin: 0.5em 0;
  border-radius: 1em;
  display: flex;
  flex-direction: column;
  gap: 0.8em;
}
.list-item {
  border-radius: 0.5em;
  padding: 0.8em;
  display: flex;
  align-items: center;
  gap: 0.8em;
  background: #ffffff;
  box-shadow: 0.1em 0.1em 0.2em #0000002f;
}
.list-item.active:hover {
  transform: scale(1.02);
  filter: brightness(105%);
  cursor: pointer;
}
.list-item > .logo {
  width: 2.5em;
  height: 2.5em;
}
.list-item > .logo > img {
  width: 100%;
  height: 100%;
  object-fit: contain;
}
.list-item > .name {
  font-size: 0.9em;
  width: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
}
.list-item > .name > .sub-title {
  opacity: 0.5;
  font-size: 0.6em;
}
.list-item > .action {
  opacity: 0.5;
}
@media (orientation: landscape) {
  .project-list {
    padding: 1.5em 2.5em;
  }
  .list-item {
    padding: 0.8em 2em;
  }
}
</style>
