// src/components/content-section/skills.vue
<script setup lang="ts">
import { ref, watch } from "vue"
import { useWindowSize } from "@vueuse/core"

const chartRef = ref()
const { width, height } = useWindowSize()
 const chartOptions = {
    chart: {
      type: "radar",
      toolbar: {
        show: false
      }
    },
    markers: {
      size: 0
    },
    tooltip: {
      enabled: false
    },
    xaxis: {
      categories: ["Responsiveness" , "Frontend", "Layout",  "Backend", "Graphics"]
    }
  }

  const series = [
    {
      name: "Statistic",
      data: [95, 75, 98, 40, 80]
    }
  ]

  watch([width, height], () => {
    chartRef.value?.resize()
  })
</script>
<template>
  <section id="skill">
    <div class="section-title">Skills</div>
    <div class="tools">
      <div class="item">
        <div class="icon">
          <img src="@/assets/img/logo/gitlab.webp" alt="gitlab">
        </div>
        <div class="label">Gitlab</div>
      </div>
      <div class="item">
        <div class="icon">
          <img src="@/assets/img/logo/github.webp" alt="github">
        </div>
        <div class="label">Github</div>
      </div>
      <div class="item">
        <div class="icon">
          <img src="@/assets/img/logo/vue.webp" alt="vue">
        </div>
        <div class="label">VueJS</div>
      </div>
      <div class="item">
        <div class="icon">
          <img src="@/assets/img/logo/react.webp" alt="reactjs">
          <div class="remarks">Entry</div>
        </div>
        <div class="label">ReactJS</div>
      </div>
      <div class="item">
        <div class="icon">
          <img src="@/assets/img/logo/next.webp" alt="nextjs">
          <div class="remarks">Entry</div>
        </div>
        <div class="label">NextJS</div>
      </div>
      <div class="item">
        <div class="icon">
          <img src="@/assets/img/logo/node.webp" alt="node">
        </div>
        <div class="label">NodeJS</div>
      </div>
      <div class="item">
        <div class="icon">
          <img src="@/assets/img/logo/typescript.webp" alt="typescript">
        </div>
        <div class="label">Typescript</div>
      </div>
      <div class="item">
        <div class="icon">
          <img src="@/assets/img/logo/photoshop.webp" alt="photoshop">
        </div>
        <div class="label">Photoshop</div>
      </div>
      <div class="item">
        <div class="icon">
          <img src="@/assets/img/logo/html5.webp" alt="html5">
        </div>
        <div class="label">html5</div>
      </div>
      <div class="item">
        <div class="icon">
          <img src="@/assets/img/logo/css3.webp" alt="css3">
        </div>
        <div class="label">css3</div>
      </div>
    </div>
    <div class="section-title">Web Development Statistic</div>
    <div class="chart-wrapper">
      <apexchart
        type="radar"
        width="100%"
        height="100%"
        :options="chartOptions"
        :series="series"
      />
    </div>
  </section>
</template>
<style scoped>
section#skill {
  background: linear-gradient(45deg, #00086d, #962121);
  padding-bottom: 0;
}
section#skill .section-title {
  background: transparent;
}
.tools {
  background: #f0f0f0;
  padding: 2em 1em;
  border-radius: 1em;
  width: 100%;
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  font-size: 0.6em;
  text-align: center;
  justify-content: center;
  margin-bottom: 1em;
  gap: 1em;
  color: #ffffff;
  background: linear-gradient(to bottom, #2323234d, #2f80dc4b);
}
.tools > .item {
  width: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  gap: 0.3em;
}
.tools > .item > .icon {
  width: 80%;
  aspect-ratio: 1/1;
  padding: 0.5em;
  border-radius: 0.6em;
  background: #ffffff;
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
}
.tools > .item > .icon .remarks {
  position: absolute;
  background: rgb(101, 101, 101);
  top: -1em;
  right: -1em;
  font-size: 0.7em;
  border-radius: 0.5em;
  padding: 0 0.5em;

}
.tools > .item > .icon > img {
  width: 100%;
  height: auto;
  aspect-ratio: 1/1;
}
.chart-wrapper {
  width: 80vw;
  height: 80vw;
  margin: auto;
  margin-top: -2.5em;
}
::v-deep(.vue-apexcharts),
::v-deep(.apexcharts-canvas > svg ) {
  width: 100% !important;
}
@media (orientation: landscape) {
  .tools {
    grid-template-columns: repeat(10, 1fr);
  }
  .chart-wrapper {
    height: 30vw;
    width: 30vw;
  }
}
</style>

// src/components/skills.tsx
"use client"
import Styles from "@/src/css/skills.module.css"
import Image from "next/image"
import { RadarChart } from '@mui/x-charts/RadarChart';
// Image
import gitlabLogo from "@/public/assets/img/logo/gitlab.webp"
import githubLogo from "@/public/assets/img/logo/github.webp"
import vueLogo from "@/public/assets/img/logo/vue.webp"
import reactLogo from "@/public/assets/img/logo/react.webp"
import nextLogo from "@/public/assets/img/logo/next.webp"
import nodeLogo from "@/public/assets/img/logo/node.webp"
import typescriptLogo from "@/public/assets/img/logo/typescript.webp"
import photoshopLogo from "@/public/assets/img/logo/photoshop.webp"
import html5Logo from "@/public/assets/img/logo/html5.webp"
import css3Logo from "@/public/assets/img/logo/css3.webp"

export function MultiSeriesRadar() {
  return (
        <RadarChart
        series={[{ 
            data: [95, 75, 98, 40, 80],
            color: '#71c6ff',
        }]}
        radar={{
            max: 100,
            metrics: ['Responsiveness', 'Frontend', 'Layout', 'Backend', 'Graphics']
        }}
        sx={{
        '& text, & .MuiChartsRadar-metricLabel': {
          fill: '#ffffffd7 !important'
        },
        '& .MuiRadarChart-gridDivider': {
            stroke: 'rgba(255, 255, 255, 0.74) !important'
        },
        '& .MuiRadarChart-seriesArea': {
            fill: '#4da0e8 !important',
            fillOpacity: '0.15 !important',
            stroke: '#71c6ff'
        },
      }}
    />
  );
}

const Skill = () => {
    return (
        <>
        <div className={Styles.sectionTitle}>Skills</div>
        <div className={Styles.tools}>
            <div className={Styles.item}>
                <div className={Styles.icon}>
                    <Image src={gitlabLogo} alt="gitlab"/>
                </div>
                <div className={Styles.label}>Gitlab</div>
            </div>
            <div className={Styles.item}>
                <div className={Styles.icon}>
                    <Image src={githubLogo} alt="github"/>
                </div>
                <div className={Styles.label}>Github</div>
            </div>
            <div className={Styles.item}>
                <div className={Styles.icon}>
                    <Image src={vueLogo} alt="vue"/>
                </div>
                <div className={Styles.label}>VueJS</div>
            </div>
            <div className={Styles.item}>
                <div className={Styles.icon}>
                    <Image src={reactLogo} alt="reactjs"/>
                </div>
                <div className={Styles.label}>ReactJS</div>
            </div>
            <div className={Styles.item}>
                <div className={Styles.icon}>
                    <Image src={nextLogo} alt="nextjs"/>
                </div>
                <div className={Styles.label}>NextJS</div>
            </div>
            <div className={Styles.item}>
                <div className={Styles.icon}>
                    <Image src={nodeLogo} alt="node"/>
                </div>
                <div className={Styles.label}>NodeJS</div>
            </div>
            <div className={Styles.item}>
                <div className={Styles.icon}>
                    <Image src={typescriptLogo} alt="typescript"/>
                </div>
                <div className={Styles.label}>Typescript</div>
            </div>
            <div className={Styles.item}>
                <div className={Styles.icon}>
                    <Image src={photoshopLogo} alt="photoshop"/>
                </div>
                <div className={Styles.label}>Photoshop</div>
            </div>
            <div className={Styles.item}>
                <div className={Styles.icon}>
                    <Image src={html5Logo} alt="html5"/>
                </div>
                <div className={Styles.label}>html5</div>
            </div>
            <div className={Styles.item}>
                <div className={Styles.icon}>
                    <Image src={css3Logo} alt="css3"/>
                </div>
                <div className={Styles.label}>css3</div>
            </div>
        </div>
        <div className={Styles.sectionTitle}>Web Development Statistic</div>
        <div className={Styles.chartWrapper}>
            {MultiSeriesRadar()}
            </div>
        </>

    )
}

export default Skill
